package cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-11-16T15:33:13.427+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "", name = "AppointmentSvcHttpGet")
@XmlSeeAlso({generated.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AppointmentSvcHttpGet {

    @WebResult(name = "string", targetNamespace = "", partName = "Body")
    @WebMethod(operationName = "GetAppointmentResult")
    public java.lang.String getAppointmentResult(
        @WebParam(partName = "strJson", name = "strJson", targetNamespace = "")
        java.lang.String strJson
    );
}
