package cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-11-16T15:33:13.317+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "", name = "AppointmentSvcSoap")
@XmlSeeAlso({generated.ObjectFactory.class})
public interface AppointmentSvcSoap {

    @WebResult(name = "GetAppointmentResultResult", targetNamespace = "")
    @RequestWrapper(localName = "GetAppointmentResult", targetNamespace = "", className = "generated.GetAppointmentResult")
    @WebMethod(operationName = "GetAppointmentResult", action = "/GetAppointmentResult")
    @ResponseWrapper(localName = "GetAppointmentResultResponse", targetNamespace = "", className = "generated.GetAppointmentResultResponse")
    public java.lang.String getAppointmentResult(
        @WebParam(name = "strJson", targetNamespace = "")
        java.lang.String strJson
    );
}
